name: rual
favicon: null
layout_spectrum: 1
typography_spectrum: 0.17397
title: Tryout
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#1f2831'
    - '#43484b'
    - '#d1d5e0'
    - '#8b929d'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.6635204930789769
purpose: []
